### PR TITLE
Make gics static table

### PR DESCRIPTION
**Pull request by rnguillory**
Test by running DROPs only in master branch "Create_Tables.sql", run "external_data/GICS_Inserts.sql", then run "Create_Tables.sql" in "make_gics_static_table" branch.

Once this is working, we probably should adapt the "Inserts.sql" to use values in the externally generated GICS table, and remove the GICS INSERTs from "Inserts.sql".

### CODE REVIEW

**Comment by JeriMarch** [comment]
Looks good!  Go ahead and merge in your pull request. I'm going to make a in issue for adapting inserts.sql to these changes with the external GICS table.

**Comment by JeriMarch** [comment]
Note: All I did was run the Create Tables and Inserts. Wasn't sure if you'd made anything that gave output.

**Comment by gtrj0527** [comment]
Gaby is merging it in. GTG!

**Comment by rnguillory** [comment]
Nah, no output.  No access to IntelliJ.

**Comment by JeriMarch** [comment]
No worries.  Your branch is merged in to master.

________________________________

**Pull request merged**
